// Code generated by ent, DO NOT EDIT.

package userinput

import (
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the userinput type in the database.
	Label = "userinput"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldMin holds the string denoting the min field in the database.
	FieldMin = "min"
	// FieldMax holds the string denoting the max field in the database.
	FieldMax = "max"
	// FieldStep holds the string denoting the step field in the database.
	FieldStep = "step"
	// FieldDefaultval holds the string denoting the defaultval field in the database.
	FieldDefaultval = "defaultval"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// Table holds the table name of the userinput in the database.
	Table = "userinputs"
)

// Columns holds all SQL columns for userinput fields.
var Columns = []string{
	FieldID,
	FieldMin,
	FieldMax,
	FieldStep,
	FieldDefaultval,
	FieldName,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)
