// Code generated by ent, DO NOT EDIT.

package datapoint

import (
	"time"

	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the datapoint type in the database.
	Label = "datapoint"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldDataTime holds the string denoting the data_time field in the database.
	FieldDataTime = "data_time"
	// FieldParameterID holds the string denoting the parameter_id field in the database.
	FieldParameterID = "parameter_id"
	// FieldVal holds the string denoting the val field in the database.
	FieldVal = "val"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// EdgeParameters holds the string denoting the parameters edge name in mutations.
	EdgeParameters = "parameters"
	// Table holds the table name of the datapoint in the database.
	Table = "datapoints"
	// ParametersTable is the table that holds the parameters relation/edge.
	ParametersTable = "datapoints"
	// ParametersInverseTable is the table name for the Parameter entity.
	// It exists in this package in order to avoid circular dependency with the "parameter" package.
	ParametersInverseTable = "parameters"
	// ParametersColumn is the table column denoting the parameters relation/edge.
	ParametersColumn = "parameter_id"
)

// Columns holds all SQL columns for datapoint fields.
var Columns = []string{
	FieldID,
	FieldDataTime,
	FieldParameterID,
	FieldVal,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)
