// Code generated by ent, DO NOT EDIT.

package datapoint

import (
	"time"

	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the datapoint type in the database.
	Label = "datapoint"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldDataTime holds the string denoting the data_time field in the database.
	FieldDataTime = "data_time"
	// FieldDatasetID holds the string denoting the dataset_id field in the database.
	FieldDatasetID = "dataset_id"
	// FieldVals holds the string denoting the vals field in the database.
	FieldVals = "vals"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// EdgeDatasets holds the string denoting the datasets edge name in mutations.
	EdgeDatasets = "datasets"
	// Table holds the table name of the datapoint in the database.
	Table = "datapoints"
	// DatasetsTable is the table that holds the datasets relation/edge.
	DatasetsTable = "datapoints"
	// DatasetsInverseTable is the table name for the Dataset entity.
	// It exists in this package in order to avoid circular dependency with the "dataset" package.
	DatasetsInverseTable = "datasets"
	// DatasetsColumn is the table column denoting the datasets relation/edge.
	DatasetsColumn = "dataset_id"
)

// Columns holds all SQL columns for datapoint fields.
var Columns = []string{
	FieldID,
	FieldDataTime,
	FieldDatasetID,
	FieldVals,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)
