// Code generated by ent, DO NOT EDIT.

package datapoint

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/rodzinkaPLN/GrindingOptimalization/api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Datapoint {
	return predicate.Datapoint(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Datapoint {
	return predicate.Datapoint(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Datapoint {
	return predicate.Datapoint(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Datapoint {
	return predicate.Datapoint(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Datapoint {
	return predicate.Datapoint(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Datapoint {
	return predicate.Datapoint(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Datapoint {
	return predicate.Datapoint(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Datapoint {
	return predicate.Datapoint(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Datapoint {
	return predicate.Datapoint(sql.FieldLTE(FieldID, id))
}

// DataTime applies equality check predicate on the "data_time" field. It's identical to DataTimeEQ.
func DataTime(v time.Time) predicate.Datapoint {
	return predicate.Datapoint(sql.FieldEQ(FieldDataTime, v))
}

// ParameterID applies equality check predicate on the "parameter_id" field. It's identical to ParameterIDEQ.
func ParameterID(v uuid.UUID) predicate.Datapoint {
	return predicate.Datapoint(sql.FieldEQ(FieldParameterID, v))
}

// Val applies equality check predicate on the "val" field. It's identical to ValEQ.
func Val(v float64) predicate.Datapoint {
	return predicate.Datapoint(sql.FieldEQ(FieldVal, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Datapoint {
	return predicate.Datapoint(sql.FieldEQ(FieldCreatedAt, v))
}

// DataTimeEQ applies the EQ predicate on the "data_time" field.
func DataTimeEQ(v time.Time) predicate.Datapoint {
	return predicate.Datapoint(sql.FieldEQ(FieldDataTime, v))
}

// DataTimeNEQ applies the NEQ predicate on the "data_time" field.
func DataTimeNEQ(v time.Time) predicate.Datapoint {
	return predicate.Datapoint(sql.FieldNEQ(FieldDataTime, v))
}

// DataTimeIn applies the In predicate on the "data_time" field.
func DataTimeIn(vs ...time.Time) predicate.Datapoint {
	return predicate.Datapoint(sql.FieldIn(FieldDataTime, vs...))
}

// DataTimeNotIn applies the NotIn predicate on the "data_time" field.
func DataTimeNotIn(vs ...time.Time) predicate.Datapoint {
	return predicate.Datapoint(sql.FieldNotIn(FieldDataTime, vs...))
}

// DataTimeGT applies the GT predicate on the "data_time" field.
func DataTimeGT(v time.Time) predicate.Datapoint {
	return predicate.Datapoint(sql.FieldGT(FieldDataTime, v))
}

// DataTimeGTE applies the GTE predicate on the "data_time" field.
func DataTimeGTE(v time.Time) predicate.Datapoint {
	return predicate.Datapoint(sql.FieldGTE(FieldDataTime, v))
}

// DataTimeLT applies the LT predicate on the "data_time" field.
func DataTimeLT(v time.Time) predicate.Datapoint {
	return predicate.Datapoint(sql.FieldLT(FieldDataTime, v))
}

// DataTimeLTE applies the LTE predicate on the "data_time" field.
func DataTimeLTE(v time.Time) predicate.Datapoint {
	return predicate.Datapoint(sql.FieldLTE(FieldDataTime, v))
}

// ParameterIDEQ applies the EQ predicate on the "parameter_id" field.
func ParameterIDEQ(v uuid.UUID) predicate.Datapoint {
	return predicate.Datapoint(sql.FieldEQ(FieldParameterID, v))
}

// ParameterIDNEQ applies the NEQ predicate on the "parameter_id" field.
func ParameterIDNEQ(v uuid.UUID) predicate.Datapoint {
	return predicate.Datapoint(sql.FieldNEQ(FieldParameterID, v))
}

// ParameterIDIn applies the In predicate on the "parameter_id" field.
func ParameterIDIn(vs ...uuid.UUID) predicate.Datapoint {
	return predicate.Datapoint(sql.FieldIn(FieldParameterID, vs...))
}

// ParameterIDNotIn applies the NotIn predicate on the "parameter_id" field.
func ParameterIDNotIn(vs ...uuid.UUID) predicate.Datapoint {
	return predicate.Datapoint(sql.FieldNotIn(FieldParameterID, vs...))
}

// ParameterIDIsNil applies the IsNil predicate on the "parameter_id" field.
func ParameterIDIsNil() predicate.Datapoint {
	return predicate.Datapoint(sql.FieldIsNull(FieldParameterID))
}

// ParameterIDNotNil applies the NotNil predicate on the "parameter_id" field.
func ParameterIDNotNil() predicate.Datapoint {
	return predicate.Datapoint(sql.FieldNotNull(FieldParameterID))
}

// ValEQ applies the EQ predicate on the "val" field.
func ValEQ(v float64) predicate.Datapoint {
	return predicate.Datapoint(sql.FieldEQ(FieldVal, v))
}

// ValNEQ applies the NEQ predicate on the "val" field.
func ValNEQ(v float64) predicate.Datapoint {
	return predicate.Datapoint(sql.FieldNEQ(FieldVal, v))
}

// ValIn applies the In predicate on the "val" field.
func ValIn(vs ...float64) predicate.Datapoint {
	return predicate.Datapoint(sql.FieldIn(FieldVal, vs...))
}

// ValNotIn applies the NotIn predicate on the "val" field.
func ValNotIn(vs ...float64) predicate.Datapoint {
	return predicate.Datapoint(sql.FieldNotIn(FieldVal, vs...))
}

// ValGT applies the GT predicate on the "val" field.
func ValGT(v float64) predicate.Datapoint {
	return predicate.Datapoint(sql.FieldGT(FieldVal, v))
}

// ValGTE applies the GTE predicate on the "val" field.
func ValGTE(v float64) predicate.Datapoint {
	return predicate.Datapoint(sql.FieldGTE(FieldVal, v))
}

// ValLT applies the LT predicate on the "val" field.
func ValLT(v float64) predicate.Datapoint {
	return predicate.Datapoint(sql.FieldLT(FieldVal, v))
}

// ValLTE applies the LTE predicate on the "val" field.
func ValLTE(v float64) predicate.Datapoint {
	return predicate.Datapoint(sql.FieldLTE(FieldVal, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Datapoint {
	return predicate.Datapoint(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Datapoint {
	return predicate.Datapoint(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Datapoint {
	return predicate.Datapoint(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Datapoint {
	return predicate.Datapoint(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Datapoint {
	return predicate.Datapoint(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Datapoint {
	return predicate.Datapoint(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Datapoint {
	return predicate.Datapoint(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Datapoint {
	return predicate.Datapoint(sql.FieldLTE(FieldCreatedAt, v))
}

// HasParameters applies the HasEdge predicate on the "parameters" edge.
func HasParameters() predicate.Datapoint {
	return predicate.Datapoint(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ParametersTable, ParametersColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasParametersWith applies the HasEdge predicate on the "parameters" edge with a given conditions (other predicates).
func HasParametersWith(preds ...predicate.Parameter) predicate.Datapoint {
	return predicate.Datapoint(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(ParametersInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ParametersTable, ParametersColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Datapoint) predicate.Datapoint {
	return predicate.Datapoint(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Datapoint) predicate.Datapoint {
	return predicate.Datapoint(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Datapoint) predicate.Datapoint {
	return predicate.Datapoint(func(s *sql.Selector) {
		p(s.Not())
	})
}
