// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Datapoint is the predicate function for datapoint builders.
type Datapoint func(*sql.Selector)

// Dataset is the predicate function for dataset builders.
type Dataset func(*sql.Selector)

// Parameter is the predicate function for parameter builders.
type Parameter func(*sql.Selector)
