FROM golang:1.19.3

WORKDIR /go/src/github.com/rodzinkaPLN/GrindingOptimalization/api
RUN go install github.com/cosmtrek/air@v1.40.4

COPY ./go.mod ./go.mod
COPY ./go.sum ./go.sum

RUN go mod download

CMD [ "air" ]